#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: Kcompile <file.kl>"
    exit 1
fi

FILE="$1"

if [[ ! -f "$FILE" ]]; then
    echo "File not found: $FILE"
    exit 1
fi

echo "Running compiler on $FILE ..."

python3 src/main.py "$FILE"